### ISSUE TITLE
HHVM - 3.9 Compiling Pgsql

### ISSUE THREAD

**Issue by no1youknowz** [PocketRent/hhvm-pgsql#101]
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
	[ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
	In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:1:0:
	/root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_resource.h:4:41: fatal error: hphp/runtime/ext/pdo_driver.h: No such file or directory
	 #include "hphp/runtime/ext/pdo_driver.h"
	                                         ^
	compilation terminated.
	make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o] Error 1
	make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
	make: *** [all] Error 2

Am I missing something in building hhvm?

Thanks

**Comment by Orvid** [comment]
Yep, pdo was moved around for 3.9.

The new path for that is `hphp/runtime/ext/pdo/pdo_driver.h`

**Comment by no1youknowz** [comment]
Thanks @Orvid 

This helped also:  https://github.com/PocketRent/hhvm-pgsql/pull/96
