### ISSUE TITLE
12.04 x86_64: segfaulting hhvm when being used via nginx with DaviCAL/AWL. Kind request for compilation against latest hhvm

### ISSUE THREAD

**Issue by kakohari** [PocketRent/hhvm-pgsql#102]
hhvm --version
HipHop VM 3.6.6 (rel)
Compiler: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
Repo schema: 5034239b4e72c991556d7e651946e7fe89d8c2f4

is crashing on
<pre>
 cat /etc/os-release 
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"
uname -a
Linux extern 3.13.0-62-generic #102~precise1-Ubuntu SMP Wed Aug 12 14:09:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
</pre>
when using AWL/Davical to access pgsql.
May have crashed before the latest update (which has been installed yesterday via the hhvm-Repo deb http://dl.hhvm.com/ubuntu precise main)

Some more (or less?) useful infomation:
<pre>
uname -a
Linux extern 3.13.0-62-generic #102~precise1-Ubuntu SMP Wed Aug 12 14:09:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
</pre>
<pre>
Host: extern
ProcessID: 11359
ThreadID: 7f6ab0fff700
ThreadPID: 11365
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
DebuggerCount: 0

ThreadType: Web Request
Server_SERVER_NAME:sub.domain.com
Server: sub.domain.com
URL: /

# 0  HPHP::PDODriver::createResource(HPHP::String const&, HPHP::String const&, HPHP::String const&, HPHP
::Array const&) at /usr/bin/hhvm:0
# 1  HPHP::c_PDO_ni___construct(HPHP::ObjectData*, HPHP::String const&, HPHP::String const&, HPHP::Strin
g const&, HPHP::Variant const&) at ext_pdo.cpp:0
# 2  void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedV
alue&) at /usr/bin/hhvm:0
# 3  HPHP::TypedValue* HPHP::Native::methodWrapper<false, false>(HPHP::ActRec*) at /usr/bin/hhvm:0
# 4  void HPHP::dispatchImpl<false>() at /usr/bin/hhvm:0
# 5  HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP
::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /
usr/bin/hhvm:0
# 6  HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 7  HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 8  HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 9  HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::all
ocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, st
d::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std
::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> 
>&, bool, bool, bool) at /usr/bin/hhvm:0
# 10 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootIn
fo&, bool) at /usr/bin/hhvm:0
# 11 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 12 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std:
:shared_ptr<HPHP::FastCGIJob>, bool) at /usr/bin/hhvm:0
# 13 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::sha
red_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 14 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueD
ropVMStack>::start() at /usr/bin/hhvm:0
# 15 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 16 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 17 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 18 __clone at /lib/x86_64-linux-gnu/libc.so.6:0
</pre>

May I kindly ask for a fresh compiled binary? :-)

Kind regards
Kai

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.

**Comment by kakohari** [comment]
> hhvm-pgsql is now include in as port of the core repository
@simonwelsh Thank you for your reply and your hint - and inclusion is a very good idea!
