### ISSUE TITLE
Debian8 hhvm-nightly make error

### ISSUE THREAD

**Issue by tianweb** [PocketRent/hhvm-pgsql#104]
Scanning dependencies of target pgsql
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
/root/hhvm-pgsql/pgsql.cpp: In destructor ‘virtual HPHP::{anonymous}::PGSQLResult::~PGSQLResult()’:
/root/hhvm-pgsql/pgsql.cpp:321:13: error: ‘class HPHP::{anonymous}::PGSQL’ has no member named ‘decRefCount’
     m_conn->decRefCount();
             ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_connect(const HPHP::String&, int)’:
/root/hhvm-pgsql/pgsql.cpp:671:13: error: ‘newres’ was not declared in this scope
     pgsql = newres<PGSQL>(connection_string);
             ^
/root/hhvm-pgsql/pgsql.cpp:671:25: error: expected primary-expression before ‘>’ token
     pgsql = newres<PGSQL>(connection_string);
                         ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_pconnect(const HPHP::String&, int)’:
/root/hhvm-pgsql/pgsql.cpp:686:13: error: ‘newres’ was not declared in this scope
     pgsql = newres<PGSQL>(pool);
             ^
/root/hhvm-pgsql/pgsql.cpp:686:25: error: expected primary-expression before ‘>’ token
     pgsql = newres<PGSQL>(pool);
                         ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_query(const HPHP::Resource&, const HPHP::String&)’:
/root/hhvm-pgsql/pgsql.cpp:1120:29: error: ‘newres’ was not declared in this scope
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                             ^
/root/hhvm-pgsql/pgsql.cpp:1120:47: error: expected primary-expression before ‘>’ token
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                               ^
/root/hhvm-pgsql/pgsql.cpp:1120:68: warning: left operand of comma operator has no effect [-Wunused-value]
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                                                    ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_query_params(const HPHP::Resource&, const HPHP::String&, const HPHP::Array&)’:
/root/hhvm-pgsql/pgsql.cpp:1138:29: error: ‘newres’ was not declared in this scope
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                             ^
/root/hhvm-pgsql/pgsql.cpp:1138:47: error: expected primary-expression before ‘>’ token
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                               ^
/root/hhvm-pgsql/pgsql.cpp:1138:68: warning: left operand of comma operator has no effect [-Wunused-value]
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                                                    ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_prepare(const HPHP::Resource&, const HPHP::String&, const HPHP::String&)’:
/root/hhvm-pgsql/pgsql.cpp:1154:26: error: ‘newres’ was not declared in this scope
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                          ^
/root/hhvm-pgsql/pgsql.cpp:1154:44: error: expected primary-expression before ‘>’ token
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                                            ^
/root/hhvm-pgsql/pgsql.cpp:1154:65: warning: left operand of comma operator has no effect [-Wunused-value]
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                                                                 ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_execute(const HPHP::Resource&, const HPHP::String&, const HPHP::Array&)’:
/root/hhvm-pgsql/pgsql.cpp:1172:26: error: ‘newres’ was not declared in this scope
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                          ^
/root/hhvm-pgsql/pgsql.cpp:1172:44: error: expected primary-expression before ‘>’ token
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                                            ^
/root/hhvm-pgsql/pgsql.cpp:1172:65: warning: left operand of comma operator has no effect [-Wunused-value]
     PGSQLResult *pgres = newres<PGSQLResult>(conn, std::move(res));
                                                                 ^
/root/hhvm-pgsql/pgsql.cpp: In function ‘HPHP::Variant HPHP::f_pg_get_result(const HPHP::Resource&)’:
/root/hhvm-pgsql/pgsql.cpp:1226:29: error: ‘newres’ was not declared in this scope
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                             ^
/root/hhvm-pgsql/pgsql.cpp:1226:47: error: expected primary-expression before ‘>’ token
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                               ^
/root/hhvm-pgsql/pgsql.cpp:1226:68: warning: left operand of comma operator has no effect [-Wunused-value]
     PGSQLResult *pgresult = newres<PGSQLResult>(conn, std::move(res));
                                                                    ^
In file included from /usr/include/hphp/runtime/base/memory-manager.h:38:0,
                 from /usr/include/hphp/runtime/base/array-data.h:25,
                 from /usr/include/hphp/runtime/base/array-data-defs.h:20,
                 from /usr/include/hphp/runtime/base/array-iterator.h:23,
                 from /root/hhvm-pgsql/pgsql.cpp:4:
/usr/include/hphp/runtime/base/req-ptr.h: In instantiation of ‘bool HPHP::isa_non_null(const P&) [with T = HPHP::{anonymous}::PGSQL; P = HPHP::req::ptr<HPHP::ResourceHdr>]’:
/usr/include/hphp/runtime/base/req-ptr.h:354:26:   required from ‘HPHP::req::ptr<T> HPHP::cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQL; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/type-resource.h:135:78:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQL]’
/root/hhvm-pgsql/pgsql.cpp:210:67:   required from here
/usr/include/hphp/runtime/base/req-ptr.h:291:36: error: ‘struct HPHP::ResourceHdr’ has no member named ‘instanceof’
   return p->template instanceof<T>();
                                    ^
/usr/include/hphp/runtime/base/req-ptr.h: In instantiation of ‘void HPHP::throw_invalid_object_type(const HPHP::req::ptr<T>&) [with T = HPHP::ResourceHdr]’:
/usr/include/hphp/runtime/base/req-ptr.h:357:32:   required from ‘HPHP::req::ptr<T> HPHP::cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQL; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/type-resource.h:135:78:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQL]’
/root/hhvm-pgsql/pgsql.cpp:210:67:   required from here
/usr/include/hphp/runtime/base/req-ptr.h:280:36: error: use of deleted function ‘HPHP::Variant::Variant(const void*)’
   throw_invalid_object_type(p.get());
                                    ^
In file included from /usr/include/hphp/runtime/base/array-data-defs.h:24:0,
                 from /usr/include/hphp/runtime/base/array-iterator.h:23,
                 from /root/hhvm-pgsql/pgsql.cpp:4:
/usr/include/hphp/runtime/base/type-variant.h:192:18: note: declared here
   /* implicit */ Variant(const void*) = delete;
                  ^
In file included from /usr/include/hphp/runtime/base/memory-manager.h:38:0,
                 from /usr/include/hphp/runtime/base/array-data.h:25,
                 from /usr/include/hphp/runtime/base/array-data-defs.h:20,
                 from /usr/include/hphp/runtime/base/array-iterator.h:23,
                 from /root/hhvm-pgsql/pgsql.cpp:4:
/usr/include/hphp/runtime/base/req-ptr.h: In instantiation of ‘bool HPHP::isa_non_null(const P&) [with T = HPHP::{anonymous}::PGSQLResult; P = HPHP::req::ptr<HPHP::ResourceHdr>]’:
/usr/include/hphp/runtime/base/req-ptr.h:354:26:   required from ‘HPHP::req::ptr<T> HPHP::cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQLResult; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/type-resource.h:135:78:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQLResult]’
/root/hhvm-pgsql/pgsql.cpp:306:69:   required from here
/usr/include/hphp/runtime/base/req-ptr.h:291:36: error: ‘struct HPHP::ResourceHdr’ has no member named ‘instanceof’
   return p->template instanceof<T>();
                                    ^
/usr/include/hphp/runtime/base/req-ptr.h: In instantiation of ‘HPHP::req::ptr<T> HPHP::unsafe_cast_helper<T, P>::operator()(const P&) const [with T = HPHP::{anonymous}::PGSQL; P = HPHP::req::ptr<HPHP::ResourceHdr>]’:
/usr/include/hphp/runtime/base/req-ptr.h:322:61:   required from ‘HPHP::req::ptr<T> HPHP::unsafe_cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQL; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/req-ptr.h:380:63:   required from ‘HPHP::req::ptr<T> HPHP::dyn_cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQL; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/type-resource.h:135:53:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQL]’
/root/hhvm-pgsql/pgsql.cpp:210:67:   required from here
/usr/include/hphp/runtime/base/req-ptr.h:315:52: error: invalid static_cast from type ‘HPHP::ResourceHdr*’ to type ‘HPHP::{anonymous}::PGSQL*’
     return req::ptr<T>(static_cast<T*>(deref<T>(p)));
                                                    ^
/usr/include/hphp/runtime/base/req-ptr.h: In instantiation of ‘HPHP::req::ptr<T> HPHP::unsafe_cast_helper<T, P>::operator()(const P&) const [with T = HPHP::{anonymous}::PGSQLResult; P = HPHP::req::ptr<HPHP::ResourceHdr>]’:
/usr/include/hphp/runtime/base/req-ptr.h:322:61:   required from ‘HPHP::req::ptr<T> HPHP::unsafe_cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQLResult; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/req-ptr.h:380:63:   required from ‘HPHP::req::ptr<T> HPHP::dyn_cast_or_null(P&&) [with T = HPHP::{anonymous}::PGSQLResult; P = const HPHP::req::ptr<HPHP::ResourceHdr>&]’
/usr/include/hphp/runtime/base/type-resource.h:135:53:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQLResult]’
/root/hhvm-pgsql/pgsql.cpp:306:69:   required from here
/usr/include/hphp/runtime/base/req-ptr.h:315:52: error: invalid static_cast from type ‘HPHP::ResourceHdr*’ to type ‘HPHP::{anonymous}::PGSQLResult*’
CMakeFiles/pgsql.dir/build.make:54: recipe for target 'CMakeFiles/pgsql.dir/pgsql.cpp.o' failed
make[2]: *** [CMakeFiles/pgsql.dir/pgsql.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pgsql.dir/all' failed
make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Thank you.

**Comment by Aatch** [comment]
Fixed by 160fa5cb
