### ISSUE TITLE
when I user this extension install drupal 8.0.2, I get some error ?

### ISSUE THREAD

**Issue by javacty** [PocketRent/hhvm-pgsql#106]
http://192.168.1.11/core/install.php?langcode=zh-hans&profile=standard&continue=1
<pre>
Additional uncaught exception thrown while handling exception.

Original

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "\" LINE 1: ...ES ('hook_info', '-1', '1453533564.945', '', '0', \x613a303a... ^ : INSERT INTO cache_bootstrap (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( ) in Drupal\Core\Extension\ModuleHandler->getHookInfo() (line 287 of /opt/www/dp802/core/lib/Drupal/Core/Extension/ModuleHandler.php).

Drupal\Core\Extension\ModuleHandler->getHookInfo()
Drupal\Core\Extension\ModuleHandler->buildImplementationInfo('entity_type_build')
Drupal\Core\Extension\ModuleHandler->getImplementationInfo('entity_type_build')
Drupal\Core\Extension\ModuleHandler->getImplementations('entity_type_build')
Drupal\Core\Entity\EntityTypeManager->findDefinitions()
Drupal\Core\Plugin\DefaultPluginManager->getDefinitions()
Drupal\Core\Entity\EntityManager->getDefinitions()
Drupal\Core\Config\ConfigManager->getEntityTypeIdByName('core.extension')
Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array)
Drupal\Core\Config\ConfigInstaller->installDefaultConfig('core', 'core')
Drupal\Core\ProxyClass\Config\ConfigInstaller->installDefaultConfig('core', 'core')
drupal_install_system(Array)
install_base_system(Array)
install_run_task(Array, Array)
install_run_tasks(Array)
install_drupal(Object)
Additional

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "\" LINE 1: ... ('system_list', '-1', '1453533564.964', '', '0', \x613a323a... ^ : INSERT INTO cache_bootstrap (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( ) in system_list() (line 44 of /opt/www/dp802/core/includes/module.inc).

system_list('theme')
Drupal\Core\Extension\ThemeHandler->systemThemeList()
Drupal\Core\Extension\ThemeHandler->listInfo()
_drupal_maintenance_theme()
drupal_maintenance_theme()
install_display_output(Array, Array, Array)
_drupal_log_error(Array, 1)
_drupal_exception_handler(Object)

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
