### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by dzuelke** [PocketRent/hhvm-pgsql#107]
I'm wondering if the versioning scheme for this extension should change. Right now, the tags reflect the HHVM version rather than the version of the extension itself.

Wouldn't it better to have (just for this example, I'm starting at v10.0 to avoid confusion with the existing 3.x releases) versions 10.0, 10.1 and so forth with updates; 10.1.1 with bugfixes and so forth, and each of them targeting one or more HHVM releases?

That way, you could also provide bugfixes for existing HHVM LTS releases (your 10.1.2 fixes a bug and works on 3.9+, while 10.2 or 11.0 or whatever works with, say, 3.11+ only). Or is the plan to only ever target the "bleeding edge" and not worry about bugfixes for older versions?

HHVM doesn't seem to have a very consistent/obvious "extension API version" scheme last I checked, so not sure how easy this even is, but I'd imagine it should be possible to have it that way.

It would essentially mirror the PHP extension versioning/API layout (where an "ext-mongo" version 1.1.2 works with PHP 5.5, 5.6 and 7.0).

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
