### ISSUE TITLE
Setting Path To LibQ

### ISSUE THREAD

**Issue by ProdigyView** [PocketRent/hhvm-pgsql#108]
I am having trouble running cmake because it throws the error libq not found.

Looking through config.cmake I noticed there was files path related to Postgresql. My postgres installation is located at /usr/lib/pgsql9.4 and /usr/lib/pgsql9.4/include but when I add that file path to the directory I still get libq not found, even though its there.

How can I modify the installation path so that it finds libq?

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
