### ISSUE TITLE
HHVM v3.13.0

### ISSUE THREAD

**Issue by bolvarak** [PocketRent/hhvm-pgsql#111]
HHVM version 3.13.0 is now out, when will the pre-built extensions be available for this as I cannot compile it?

`
> # make
Scanning dependencies of target pgsql
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
[ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
[ 75%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_connection.cpp.o
[100%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql.cpp.o
Linking CXX shared library pgsql.so
Generating Repo Schema ID and Compiler ID
/bin/sh: 1: cd: can't cd to /hphp/util
CMakeFiles/pgsql.dir/build.make:162: recipe for target 'pgsql.so' failed
make[2]: *** [pgsql.so] Error 2
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pgsql.dir/all' failed
make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by hugopeixoto** [comment]
I'm having the same issue compiling the extension.
It might be a problem with the hhvm-dev package.
The problem seems to be around line 130 on the file `lib/x86_64-linux-gnu/hhvm/CMake/HPHPFunctions.cmake`.

The last two commits added the offending code, from what I can tell:
https://github.com/facebook/hhvm/commits/master/CMake/HPHPFunctions.cmake

**Comment by TheSandwichMakr** [comment]
These files are in the facebook/hhvm repo. If you clone it and take hphp/ and put it in your root it will build, however I get a segfault when running.
(from dmesg)
[12494.183556] traps: hhvm[17270] general protection ip:7febd524b4e4 sp:7febc2ff88f0 error:0 in libc-2.19.so[7febd5142000+1bb000]
[12663.851413] hhvm[17435]: segfault at 38 ip 00007f46f4959dbd sp 00007f46e27f7d00 error 4 in libc-2.19.so[7f46f4910000+1bb000]

There's also an hphp/ at /usr/include/hphp/ but it only includes .h files as it's in include (and there's one at /usr/lib but it's only to store hphpize). I'm using this for the first time, but it seems odd that it's expecting there to be a hphp/ at the root...

**Comment by simonwelsh** [comment]
This is due to facebook/hhvm#6957. Closing in favour of that.
