### ISSUE TITLE
Building on Ubuntu 16.04 HHVM 3.11.1

### ISSUE THREAD

**Issue by bolvarak** [PocketRent/hhvm-pgsql#112]
**Preface**
If you want to build this library in Ubuntu 16.04-LTS using the version of HHVM in the official repos, follow these instructions.

**Prerequisites**
`sudo apt-get install build-essential cmake cmake-extras libpq-dev postgresql-client libboost-dev libgoogle-glog-dev libdouble-conversion-dev libjemalloc-dev libtbb-dev libcurl4-gnutls-dev`

**Compiling**
`cd /tmp && git clone https://github.com/PocketRent/hhvm-pgsql.git && cd hhvm-pgsql && hphpize && cmake -DHACK_FRIENDLY=ON . && make`

**Installing**
`sudo mv pgsql.so /etc/hhvm`

Then modify your HHVM configuration file.

**Notes**
You can optionally install `libcurl4-openssl-dev` instead of `libcurl4-gnutls-dev`

**Comment by Murwa** [comment]
Thanks @bolvarak. Works.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
