### ISSUE TITLE
Pre-built version for 3.13 trusty

### ISSUE THREAD

**Issue by photodude** [PocketRent/hhvm-pgsql#113]
I'm doing some CI testing with Travis CI, I only have access to HHVM 3.13 on Trusty.

The 3.12 gives this warning `Uncaught exception: /etc/hhvm/pgsql.so was built for HHVM 3.12, and cannot be loaded with HHVM 3.13`

trying to build in Travis-CI results in `hphpize: command not found`

Please provide a current Pre-built version for HHVM 3.13 on trusty

**Comment by akuseru** [comment]
3.13 has a bug that prevents external modules from being built. see facebook/hhvm#6957 you might be able to compile against the nightly build. (3.14.0-dev)

hphpize is available in the respective `-dev` packages.

**Comment by photodude** [comment]
Thanks @akuseru I've asked the Travis-CI group to downgrade their Trusty image to 3.12 until HHVM 3.14 comes out. This is unfortunately a major annoyance and a roadblock to HHVM continuous testing.

Still wish there was a better work around for this 3.13 bug.

**Comment by andrisi** [comment]
3.14 is here, will you have a binary anytime soon? Thanks!

**Comment by simonwelsh** [comment]
Yup, hoping to build them this weekend.

**Comment by simonwelsh** [comment]
Builds for 3.14 are [now available](https://github.com/PocketRent/hhvm-pgsql/tree/releases#hhvm-3140).

**Comment by photodude** [comment]
Thank you.
