### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by kayalvizhi-g05** [PocketRent/hhvm-pgsql#114]
`hhvm: symbol lookup error: /etc/hhvm/pgsql.so: undefined symbol: _ZN4HPHP6Config7GetBoolERKNS_13IniSettingMapERKNS_3HdfERKSsbb`

The above error is shown when running `make test` after building pgsql.so.
HHVM version is 3.13.1

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
