### ISSUE TITLE
Fatal error: Call to undefined function pg_set_error_verbosity() with Pre-built version for 3.12 trusty

### ISSUE THREAD

**Issue by photodude** [PocketRent/hhvm-pgsql#115]
Working on HHVM testing with pgsql I got the following error with Pre-built version for 3.12 trusty

`Fatal error: Call to undefined function pg_set_error_verbosity()`

build demonstrating the error
https://travis-ci.org/photodude/joomla-cms/jobs/132726691

I understand that the `pg_set_error_verbosity()` function is not implemented for various reasons... What is the work around for this? This missing function is causing problems for our [PostgreSQL driver connection function at line 140](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/postgresql.php#L103-L143).

Looks like we have another issue due to the `pg_set_client_encoding()` function not being implemented for various reasons... `Fatal error: Call to unimplemented native function pg_set_client_encoding() in /joomla-cms/libraries/joomla/database/driver/postgresql.php on line 890`

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
