### ISSUE TITLE
Uncaught exception: /etc/hhvm/extensions/pgsql.so was built for HHVM 3.14, and cannot be loaded with HHVM 3.15

### ISSUE THREAD

**Issue by donutloop** [PocketRent/hhvm-pgsql#117]
HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g00aa638773bc88f184e1591b3a78409362107de2
Repo schema: 59d9a08878e63351dbe86248b2032b04a41d6282

Hey, i cannot any more load the postgres extension ( https://github.com/PocketRent/hhvm-pgsql )

Uncaught exception: /etc/hhvm/extensions/pgsql.so was built for HHVM 3.14, and cannot be loaded with HHVM 3.15

Best regards,

Marcel

**Comment by simonwelsh** [comment]
We don't provide binaries for nightly versions of HHVM. If you want to use the nightly version of HHVM, you'll need to compile the extension yourself.
