### ISSUE TITLE
Building & Installation on Ubuntu 16.04 (HHVM-3.15-Nightly)

### ISSUE THREAD

**Issue by HTTP4** [PocketRent/hhvm-pgsql#118]
i want to build this library in Ubuntu 16.04-LTS using the version of HHVM 3.15 Nightly in the official repos.

How can i build it for a nightly ?

**Comment by HTTP4** [comment]
Can someone help me ?

**Comment by simonwelsh** [comment]
As of 2016-08-27, the `hhvm-nightly` packages now come with pgsql support inbuilt.
