### ISSUE TITLE
PDO when abstracted by OOP Query Builder returns no object with error 00000

### ISSUE THREAD

**Issue by Simpliant** [PocketRent/hhvm-pgsql#119]
Error Number: 00000
SELECT "data" FROM "ci_sessions" WHERE "id" = 'redacted'
CI Filename: libraries/Session/drivers/Session_database_driver.php
```
if ( ! ($result = $this->_db->get()) OR ($result = $result->row()) === NULL) 
```
Throws 00000 (means "OK") no error / 0 rows in select, end result is get() failed vs. $result = FALSE.

HipHop VM 3.11.1 (rel) + https://github.com/PocketRent/hhvm-pgsql - PostgreSQL 9.5
hhvm-pgsql extension can only be summoned in CI as 'pdo' in the config/database.php and not 'prostgre'

Same query running form cli.
```
db=#  SELECT "data" FROM "ci_sessions" WHERE "id" = 'redacted'
db-# ;
 data 
------
(0 rows)
```
00000 code is thrown because the result set is fine, however 0 rows are returned. Code-Ignighter Team kicked it here...

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
