### ISSUE TITLE
describe how to install prerequisites on various supported platforms

### ISSUE THREAD

**Issue by rrh** [PocketRent/hhvm-pgsql#40]
The README.md could be improved with a set of recipes for various *nux systems on how to install the prereqs for building this extension.

On ubuntu, empirically at least, it seems that
  sudo apt-get install libpq-dev libpq5
does the trick, but this may not be quite right.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
