### ISSUE TITLE
pgsql no longer compiles

### ISSUE THREAD

**Issue by rrh** [PocketRent/hhvm-pgsql#47]
pgsql no longer compiles against HEAD of hhvm master.

Here's the 1st handful of lines:

/home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:7:17: error: cannot declare variable ‘HPHP::s_pgsql_driver’ to be of abstract type ‘HPHP::PDOPgSql’
 static PDOPgSql s_pgsql_driver;
                 ^
In file included from /home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:1:0:
/home/rrh/dev/hphp-pgsql/pdo_pgsql.h:8:7: note:   because the following virtual functions are pure within ‘HPHP::PDOPgSql’:
 class PDOPgSql : public PDODriver {
       ^
In file included from /home/rrh/dev/hphp-pgsql/pdo_pgsql.h:5:0,
                 from /home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:1:
/usr/local/include/hphp/runtime/ext/pdo_driver.h:235:24: note: 	virtual HPHP::PDOResource* HPHP::PDODriver::createResourceImpl()
   virtual PDOResource* createResourceImpl() = 0;

**Comment by simonwelsh** [comment]
Is caused by facebook/hhvm@fc57e01

**Comment by rrh** [comment]
Thanks very much for fixing this.
