### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sosso** [PocketRent/hhvm-pgsql#48]
Can you push a new pgsql.so file?

**Comment by f8bar** [comment]
+1

**Comment by bountin** [comment]
Also a merge of the outstanding MRs would be great! /cc @simonwelsh

**Comment by simonwelsh** [comment]
Have pushed builds for HHVM 3.6.0 for Debian 8 and Ubuntu 14.04. Ubuntu 12.04 will come when the HHVM-3.6 branch is pushed publicly (needs a change that currently hasn't landed to allow building HHVM).
