### ISSUE TITLE
Build failed with HHVM 3.6.0

### ISSUE THREAD

**Issue by Chewbye** [PocketRent/hhvm-pgsql#54]
Hello,

I followed the "building and installation" section but I have an error when I exectue the "make" command:

/home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp: In constructor ‘HPHP::PDOPgSqlStatement::PDOPgSqlStatement(HPHP::PDOPgSqlConnection*, PQ::Connection*)’:
/home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:17:19: error: no match for ‘operator=’ (operand types are ‘HPHP::sp_PDOResource {aka HPHP::SmartPtr<HPHP::PDOResource>}’ and ‘HPHP::PDOPgSqlConnection*’)
         this->dbh = pdoconn;
                   ^
/home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:17:19: note: candidates are:
In file included from /usr/local/include/hphp/runtime/base/type-string.h:20:0,
                 from /usr/local/include/hphp/runtime/base/debuggable.h:19,
                 from /usr/local/include/hphp/runtime/ext/extension.h:21,
                 from /usr/local/include/hphp/runtime/base/base-includes.h:24,
                 from /usr/local/include/hphp/runtime/ext/pdo_driver.h:21,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.h:4,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:1:
/usr/local/include/hphp/runtime/base/smart-ptr.h:80:13: note: HPHP::SmartPtr<T>& HPHP::SmartPtr<T>::operator=(const HPHP::SmartPtr<T>&) [with T = HPHP::PDOResource]
   SmartPtr& operator=(const SmartPtr<T>& src) {
             ^
/usr/local/include/hphp/runtime/base/smart-ptr.h:80:13: note:   no known conversion for argument 1 from ‘HPHP::PDOPgSqlConnection*’ to ‘const HPHP::SmartPtr<HPHP::PDOResource>&’
/usr/local/include/hphp/runtime/base/smart-ptr.h:84:13: note: HPHP::SmartPtr<T>& HPHP::SmartPtr<T>::operator=(HPHP::SmartPtr<T>&&) [with T = HPHP::PDOResource]
   SmartPtr& operator=(SmartPtr&& src) {
             ^
/usr/local/include/hphp/runtime/base/smart-ptr.h:84:13: note:   no known conversion for argument 1 from ‘HPHP::PDOPgSqlConnection*’ to ‘HPHP::SmartPtr<HPHP::PDOResource>&&’
/usr/local/include/hphp/runtime/base/smart-ptr.h:91:13: note: template<class Y> HPHP::SmartPtr<T>& HPHP::SmartPtr<T>::operator=(const HPHP::SmartPtr<Y>&) [with Y = Y; T = HPHP::PDOResource]
   SmartPtr& operator=(const SmartPtr<Y>& src) {
             ^
/usr/local/include/hphp/runtime/base/smart-ptr.h:91:13: note:   template argument deduction/substitution failed:
/home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:17:19: note:   mismatched types ‘const HPHP::SmartPtr<T>’ and ‘HPHP::PDOPgSqlConnection*’
         this->dbh = pdoconn;
                   ^
In file included from /usr/local/include/hphp/runtime/base/type-string.h:20:0,
                 from /usr/local/include/hphp/runtime/base/debuggable.h:19,
                 from /usr/local/include/hphp/runtime/ext/extension.h:21,
                 from /usr/local/include/hphp/runtime/base/base-includes.h:24,
                 from /usr/local/include/hphp/runtime/ext/pdo_driver.h:21,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.h:4,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:1:
/usr/local/include/hphp/runtime/base/smart-ptr.h:96:13: note: template<class Y> HPHP::SmartPtr<T>& HPHP::SmartPtr<T>::operator=(HPHP::SmartPtr<Y>&&) [with Y = Y; T = HPHP::PDOResource]
   SmartPtr& operator=(SmartPtr<Y>&& src) {
             ^
/usr/local/include/hphp/runtime/base/smart-ptr.h:96:13: note:   template argument deduction/substitution failed:
/home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:17:19: note:   mismatched types ‘HPHP::SmartPtr<T>’ and ‘HPHP::PDOPgSqlConnection*’
         this->dbh = pdoconn;
                   ^
In file included from /usr/local/include/hphp/runtime/base/type-string.h:20:0,
                 from /usr/local/include/hphp/runtime/base/debuggable.h:19,
                 from /usr/local/include/hphp/runtime/ext/extension.h:21,
                 from /usr/local/include/hphp/runtime/base/base-includes.h:24,
                 from /usr/local/include/hphp/runtime/ext/pdo_driver.h:21,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.h:4,
                 from /home/louk/Téléchargements/hhvm-pgsql-master/pdo_pgsql_statement.cpp:1:
/usr/local/include/hphp/runtime/base/smart-ptr.h:105:13: note: HPHP::SmartPtr<T>& HPHP::SmartPtr<T>::operator=(T*) [with T = HPHP::PDOResource]
   SmartPtr& operator=(T* px) {
             ^
/usr/local/include/hphp/runtime/base/smart-ptr.h:105:13: note:   no known conversion for argument 1 from ‘HPHP::PDOPgSqlConnection*’ to ‘HPHP::PDOResource*’
make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/pgsql.dir/all] Erreur 2
make: *** [all] Erreur 2

Have i done something wrong?...

**Comment by bountin** [comment]
Hi,
hhvm changed their PDO interfaces with 3.5, so the current hhvm-pgsql code doesn't work anymore. Fortunately, there's a PR to fix it: #53. Just merge it into your working copy and everything should work again!

**Comment by Chewbye** [comment]
That worked, thank you!
