### ISSUE TITLE
pg_fetch_assoc returns NULL at end of result instead of FALSE

### ISSUE THREAD

**Issue by dstelter** [PocketRent/hhvm-pgsql#56]
As documented in [1], pg_fetch_assoc should return false if there are no more rows. The current implementation, however, returns NULL.

This also affects pg_fetch_object, as it uses pg_fetch_assoc internally.

[1] http://php.net/manual/de/function.pg-fetch-assoc.php

**Comment by mssola** [comment]
I can reproduce this issue.

**Comment by mssola** [comment]
As discussed in the PR #57, this is more a problem in regards the return type defined for some functions in the `ext_pgsql.php` file. I'll try to come up with a patch that fixes this asap.
