### ISSUE TITLE
pg_query_params overwrites parameters when values are in a certain range

### ISSUE THREAD

**Issue by dstelter** [PocketRent/hhvm-pgsql#59]
Consider this code:
> $res = pg_query_params($conn, 'SELECT $1::int, $2::int', [3969, 9999999]);
> var_dump(pg_fetch_array($res, NULL, PGSQL_NUM));

Expected outcome:
> array(2) {
>  [0] =>
>  string(4) "3969"
>  [1] =>
>  string(7) "9999999"
>}

Actual outcome:
> array(2) {
>  [0]=>
>  string(7) "9999999"
>  [1]=>
>  string(7) "9999999"
>}

i.e. the first parameter is somehow overwritten.

Some testing showed that this behavior only appears if both parameters are between 3968 and 9999999 (both inclusive)...

**Comment by dstelter** [comment]
I have traced the issue to CStringArray in pgsql.cpp. It constructs a const char* array, which references C-style string pointers of stack-local temporary objects. When these strings get destructed after the constructor returns the pointers probably point to undefined memory contents.

dstelter/hhvm-pgsql@4d6f92fc2b93060541002c81d01a7eb0bf8018bf should fix this issue.

**Comment by mssola** [comment]
It looks like I cannot reproduce your issue, but this time is probably my fault :/ Take a look at this gist: https://gist.github.com/mssola/6d5e5469e85ebb5884f1 . This is what I'm using, but I'm getting the following error:

```bash
Warning: pg_query_params(): Query failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xed 0xa7 0xc0
 in /home/mssola/Downloads/example/overwritten.php on line 11
bool(false)
```

The whole thing works as expected (therefore not reproducing your issue) if instead of integers I wrap them in strings (as in '3969'). Could you give me a hint about what am I doing wrong ? :P

**Comment by dstelter** [comment]
I believe you can actually reproduce the issue, your system just behaves differently. :-)

These two lines are the issue:
> m_strings.push_back(param.toString());
> m_c_strs.push_back(param.toString().data());

The result of String.data() may only used as long as the String object is still allocated.
The second param.toString() creates a local object that is not preserved after returning from the constructor. Therefore, the data() return value now points to invalid memory.
My fix prevents this issue by using data() of the String that is persisted in m_strings.

If you pass the parameters  as strings, the .toString() call will (probably?) return the input.
This is still being kept in memory, so the pointers in CStringArray are valid even after returning.

**Comment by mssola** [comment]
> I believe you can actually reproduce the issue, your system just behaves differently. :-)

Fair enough :-)

> The result of String.data() may only be used as long as the String object is still allocated.
The second param.toString() creates a local object that is not preserved after returning from the constructor. Therefore, the data() return value now points to invalid memory.
My fix prevents this issue by using data() of the String that is persisted in m_strings.

> If you pass the parameters as strings, the .toString() call will (probably?) return the input.
This is still being kept in memory, so the pointers in CStringArray are valid even after returning.

It makes sense, and I'd like to see a PR of this. Good job!

**Comment by mssola** [comment]
There was definitely something wrong about my gist, and now I can execute it without problems. I don't reproduce your problem, but I guess that it depends on the machine. Anyways your patch is safer than the actual code, so +1 from me.
