### ISSUE TITLE
Build time error with specific commit.

### ISSUE THREAD

**Issue by estebanmatias92** [PocketRent/hhvm-pgsql#62]
I don't know why, but with the last commit (21066200557b2a5c41835b4b434daf94f3901555) i got a build time error in pdo_pgsql_statement.cpp file.

```
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
[ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
[91mIn file included from /tmp/hhvm-extension/pdo_pgsql_statement.cpp:1:0:
[0m
[91m/tmp/hhvm-extension/pdo_pgsql_resource.h:11:49: error: expected class-name before '{' token
[0m
[91m     class PDOPgSqlResource : public PDOResource {
...
```
You can see the entire log [here](https://registry.hub.docker.com/u/estebanmatias92/hhvm-improved/build_id/41626/code/btelhpb9hv9hwgo4gdlgbdh) in the end of the page.

Thanks in advance.

**Comment by simonwelsh** [comment]
Are you trying to compile against 3.5.0? You'll need to use the commit before that in in that case.

**Comment by estebanmatias92** [comment]
My bad.

Thanks @simonwelsh.
