### ISSUE TITLE
unimplemented native function pg_get_notify

### ISSUE THREAD

**Issue by dstelter** [PocketRent/hhvm-pgsql#66]
> Fatal error: Call to unimplemented native function pg_get_notify()

The function seems to be defined in php/hh, but is never actually implemented in the module.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
