### ISSUE TITLE
undefined symbol: _ZTIN4HPHP11PDOResourceE\n

### ISSUE THREAD

**Issue by hozdemir** [PocketRent/hhvm-pgsql#69]
i'm using hhvm 3.5.1 on ubuntu 14.04

i compiled the extension and after restart hhvm;

service hhvm restart
 * Restarting HHVM FastCGI Daemon hhvm                                                                                                                                                   Uncaught exception: Could not open extension /usr/lib/hhvm/extensions/pgsql.so: /usr/lib/hhvm/extensions/pgsql.so: undefined symbol: _ZTIN4HPHP11PDOResourceE\n

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
