### ISSUE TITLE
Deletion fetchErr function in @9d937c90ed

### ISSUE THREAD

**Issue by gandikun** [PocketRent/hhvm-pgsql#73]
Sorry before,

I face some issue when i ran some of my script test : 
```This driver doesn't support fetchErr```

So i search into it, and found this commit @9d937c90ed deleted it.

I managed to put it back and successfully compiled it, so i wonder something.

If any reason to delete it? i mean from the commit message didn't explain more detail about this deletion.

Thank you before.

Regard,
 Gandi.

**Comment by jjeising** [comment]
This causes all error messages related to connection problems and similar exceptions to show this error messages instead of the original error.

**Comment by gandikun** [comment]
Do you have any example how to reproduce error that you've said? as i need this function and so far after i put it back i can't find any issue with it.

**Comment by Lykegenes** [comment]
Interested in this too. Would be much easier to debug Laravel projects

**Comment by jjeising** [comment]
@gandikun Sorry, was just emphasizing your point, talking about the error message `This driver doesn't support fetchErr`.

**Comment by gandikun** [comment]
@Lykegenes Yeah we face this issue with Laravel framework, but some debuging during tests failed.

@jjeising So here my completed story : 

I directly compiled the module, implemented it and run my test script.
but got error
```
There was 1 error:

---------
1) Dashboard\ArticlesControllerTest::test_update
Illuminate\Database\QueryException: This driver doesn't support fetchErr (SQL: insert into "article_media" ("article_id", "media_id", "order") values (332, 1, 1))
```


So I and our team like think there are some change that remove this function , and that true from this commit @9d937c9 . We found the commit deleted it, so we tried to put it back and recompiled. It's success to compile (without any problem).

So came to our consideration is, why in first place that commit delete it?
Because the commit description said to fix issue #47 
So we kind wanna know, if there was special reasons, like security issue or what? We very concern about how things work and why don't.

**Comment by digirew** [comment]
Also having the same error 
"This driver doesn't support fetchErr"

This is on a Laravel 4.2 project, but i suspect it's the pgsql driver itself not handling the error feedback properly.

**Comment by Sander-Toonen** [comment]
Having the same problem when using HHVM 3.6.0 with the precompiled trusty binary in a project using Doctrine.

**Comment by gandikun** [comment]
Here my worked fork, 
https://github.com/KMK-ONLINE/hhvm-pgsql/tree/codeception

I not pull request yet, cause i still not get the answer. so somehow I end up with maintenance own branch :(

**Comment by Mirza-dMags** [comment]
Same issue here. Is there any fix for soon future ?

**Comment by Mirza-dMags** [comment]
@gandikun i'm having same error with your fork too.

**Comment by Chewbye** [comment]
I'm having the same error with HHVM 3.6.0 when I use the pdo function errorInfo(). Is this function implemented?

$this->bdd = new PDO('pgsql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USERNAME, DB_PASSWD);
$this->bdd->query($sql);
var_dump($this->bdd->errorInfo()); //error here: 'This driver doesn't support fetchErr'

**Comment by Chewbye** [comment]
I'm having the same error with HHVM 3.6.0 using the pdo function errorInfo():
$resultat = $this->db->prepare($sql); 
		if ($resultat->execute($params)) {   
			return $resultat->fetch(PDO::FETCH_ASSOC);
		}

		return $resultat->errorInfo(); // error here: 'This driver doesn't support fetchErr'

**Comment by no1youknowz** [comment]
I had this exact same problem.  I wondered why my Codeigniter app didn't have this issue whereas my slim app did.  Turns out Codeigniter was using pg_ functions.  

I have mocked up something for you guys to use, if you want to switch:

    https://gist.github.com/no1youknowz/c994204e9ad3b3a5a601

I'm using this in my slim app and working for my needs.  Your mileage my vary and this code is totally unsupported.

**Comment by gandikun** [comment]
@Mirza-dMags , which hhvm version you used? I use my branch (already catch up for hhvm 3.7) for hhvm 3.7.2 and worked perfectly. For your error, i not sure about that. Sorry for late response, I not often open my github notification since i busy with my jobs.

**Comment by ctrlcctrlv** [comment]
Same issue here.

Here is my extremely simple script:

```php
<?php

$pdo = new PDO('pgsql:host=localhost;port=5432;dbname=db1;user=nope;password=nope');

$query = $pdo->prepare('select column_name, data_type, character_maximum_length from INFORMATION_SCHEMA.COLUMNS where table_name = \'banners\'');
$query->execute();

$result = $query->fetchAll();

print_r($result);
```
Fails with
```
Fatal error: Uncaught exception 'PDOException' with message 'This driver doesn't support fetchErr' in :
Stack trace:
#0 /var/www/test.php(3): PDO->__construct()
#1 {main}

shell returned 255
```

How is one supposed to use this library if it doesn't support `fetch`? The PDO support added in #2 is useless without `fetch`.

**Comment by xiphiaz** [comment]
@gandikun what version of HHVM does your KMK-ONLINE/hhvm-pgsql/tree/codeception for work on? I tried merging your branch into mine (see https://github.com/spira/hhvm-pgsql/pull/3) and I'm still getting the `This driver doesn't support fetchErr` issue. I'm compiling against HHVM 3.8.1

**Comment by xiphiaz** [comment]
@gandikun whoops, my mistake, your fix does work - I just built the wrong image for my testing.
