### ISSUE TITLE
pg_exec() warning different than regular PHP.

### ISSUE THREAD

**Issue by ipso** [PocketRent/hhvm-pgsql#74]
HHVM v3.6.0

PHP ERROR - WARNING(2): pg_exec() expects exactly 3 parameters, 2 given File: adodb/drivers/adodb-postgres64.inc.php Line: 181

That warning is not shown with PHP v5.5.9

Whats odd though is in the same script we see:
PHP ERROR - UNKNOWN(4096): Argument 3 passed to pg_exec() must be an instance of array, undefined variable given File: adodb/drivers/adodb-postgres64.inc.php Line: 181

No idea how its getting a 3rd argument on the same line when one is not specified at all:
return pg_Exec($this->_connectionID, "begin ".$this->_transmode);

If I change pg_exec() to pg_execute() and add a third argument of array(), so the line looks like:
return pg_execute($this->_connectionID, "begin ".$this->_transmode, array() );

PHP ERROR - WARNING(2): pg_execute(): Query failed: ERROR:  prepared statement "begin " does not exist  File: adodb/drivers/adodb-postgres64.inc.php Line: 181

In this case: $this->_transmode='' , so it should just be executing "begin", and that works fine in PHP v5.5.9, but of course fails with HHVM. 

This used to work fine back around September 2014, but this is the first time we have tested this since.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
