### ISSUE TITLE
Performance significantly worse than with stock PHP?

### ISSUE THREAD

**Issue by ipso** [PocketRent/hhvm-pgsql#75]
I've been doing some benchmarking and it seems that HHVM v3.6 with PGSQL performs significantly worse than stock PHP 5.5. 

function benchmarkQueryRaw() {
	$pgh = pg_pconnect("host=localhost port=5432 dbname=mydb user=myuser password=mypass");

	$start_timer = microtime( TRUE );

	//Test QUERY overhead.
	for( $i = 0; $i < 100; $i++ ) {
		$query = 'SELECT * FROM users LIMIT 100';
		$rs = pg_query( $pgh, $query );
		$rows = pg_num_rows( $rs );
		if ( $rows > 0 ) {
			echo "Row Count: ". $rows ."<br>\n";
			//foreach( $rs as $row ) {
				//echo "Row...<br>\n";
			//}
		} else {
			echo "NO Rows... Error: <br>\n";
		}
	}

	echo "Timer: ". ( ( microtime(TRUE) - $start_timer ) * 1000 )  ."ms <br>\n";
}
benchmarkQueryRaw();

PHP v5.5: Average over 10 runs is about 160ms
HHVM v3.6: Average over 10 runs is about 230ms

When I use ADODB, HHVM jumps to around 2 seconds for some reason, yet the exact same code with MySQL is about 150ms in both HHVM and stock PHP.  (I'm still trying to narrow down the cause of the ADODB case)

I tried to rule out any HHVM settings by testing with MySQL and confirming that HHVM is performing on par or slightly better than stock PHP there.

Am I missing something, or is this performance hit expected?

**Comment by ipso** [comment]
So I discovered why ADODB is so slow with HHVM/PGSQL, its because of this code:
for ($i=0, $max = $this->_numOfFields; $i < $max; $i++) {
	if (pg_field_type($qid,$i) == 'bytea') {
		$this->_blobArr[$i] = pg_field_name($qid,$i);
	}
}

Stock PHP runs that code on about 50 columns in 2ms, HHVM takes 10x longer at 24ms. This is with *no* 'bytea' columns at all, so I assume that pg_field_type() is horrendously slow with HHVM.

For anyone who might find this post, there is an option to disable all 'bytea' checks in ADODB, which greatly speeds things up by doing:
$db->noBlobs = TRUE; 

This is a separate issue from the above post, but still an important performance regression.

**Comment by ftzdomino** [comment]
I'm running into some performance issues with pg_field_type which would probably be helped by this todo:
https://github.com/PocketRent/hhvm-pgsql/blob/master/pgsql.cpp#L1534

**Comment by Aatch** [comment]
@ftzdomino Ah yeah. The Zend PHP version does what the comment below that says and gets all the rows and makes a map. Shouldn't actually be to difficult to implement though.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
