### ISSUE TITLE
Centos 7: make problems

### ISSUE THREAD

**Issue by no1youknowz** [PocketRent/hhvm-pgsql#76]
Trying to make this extension with centos 7 with hhvm 3.6.0.

	+ /usr/local/bin/hphpize
	** hphpize complete, now run `cmake . && make` to build, `make test` to test
	+ cmake .
	-- The C compiler identification is GNU 4.8.2
	-- The CXX compiler identification is GNU 4.8.2
	-- The ASM compiler identification is GNU
	-- Found assembler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Configuring for HHVM API version 20150212
	-- pgSQL Include dir: /usr/include
	-- libpq library: /usr/lib64/libpq.so
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql
	+ make
	Scanning dependencies of target pgsql
	[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
	[ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
	In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:4:0:
	/root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:10:35: error: conflicting return type specified for 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDOPgSql::createResourceImpl()'
	     virtual SmartPtr<PDOResource> createResourceImpl() override;
	                                   ^
	In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_resource.h:4:0,
	                 from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:1:
	/usr/local/include/hphp/runtime/ext/pdo_driver.h:235:24: error:   overriding 'virtual HPHP::PDOResource* HPHP::PDODriver::createResourceImpl()'
	   virtual PDOResource* createResourceImpl() = 0;
	                        ^
	/root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp: In member function 'bool HPHP::PDOPgSqlStatement::create(const HPHP::String&, const HPHP::Array&)':
	/root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:62:72: error: cannot convert 'HPHP::sp_PDOStatement {aka HPHP::SmartPtr<HPHP::PDOStatement>}' to 'HPHP::PDOStatement*' for argument '1' to 'int HPHP::pdo_parse_params(HPHP::PDOStatement*, const HPHP::String&, HPHP::String&)'
	             int ret = pdo_parse_params(sp_PDOStatement(this), sql, nsql);
	                                                                        ^
	make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o] Error 1
	make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
	make: *** [all] Error 2

**Comment by no1youknowz** [comment]
Compiles fine against the 3.6.0 tag.

Thanks @simonwelsh.

**Comment by no1youknowz** [comment]
Re-opening.

Cant build 3.6.x and 3.7.2 with latest master:

  [root@ip-10-0-4-42 ~]# rpmbuild -ba rpmbuild/SPECS/hhvm-pgsql.spec 
  Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.fteOMe
  + umask 022
  + cd /root/rpmbuild/BUILD
  + cd /root/rpmbuild/BUILD
  + rm -rf hhvm-ext-pgsql-1.1.0
  + /usr/bin/mkdir -p hhvm-ext-pgsql-1.1.0
  + cd hhvm-ext-pgsql-1.1.0
  + /usr/bin/gzip -dc /root/rpmbuild/SOURCES/hhvm-ext-pgsql.tar.gz
  + /usr/bin/tar -xf -
  + STATUS=0
  + '[' 0 -ne 0 ']'
  + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
  + exit 0
  Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.MfP1MD
  + umask 022
  + cd /root/rpmbuild/BUILD
  + cd hhvm-ext-pgsql-1.1.0
  + cd hhvm-ext-pgsql
  + /usr/bin/hphpize
  ** hphpize complete, now run `cmake . && make` to build, `make test` to test
  + cmake .
  -- The C compiler identification is GNU 4.8.3
  -- The CXX compiler identification is GNU 4.8.3
  -- The ASM compiler identification is GNU
  -- Found assembler: /bin/cc
  -- Check for working C compiler: /bin/cc
  -- Check for working C compiler: /bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: /bin/c++
  -- Check for working CXX compiler: /bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Configuring for HHVM API version 20150212
  -- pgSQL Include dir: /usr/include
  -- libpq library: /usr/lib64/libpq.so
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql
  + make
  Scanning dependencies of target pgsql
  [ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp: In static member function 'static HPHP::{anonymous}::PGSQL* HPHP::{anonymous}::PGSQL::Get(const HPHP::Variant&)':
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:210:69: error: request for member 'get' in 'HPHP::Variant::toResource() const().HPHP::Resource::getTyped<HPHP::{anonymous}::PGSQL>(1, 1)', which is of pointer type 'HPHP::{anonymous}::PGSQL*' (maybe you meant to use '->' ?)
       PGSQL *pgsql = conn_id.toResource().getTyped<PGSQL>(true, true).get();
                                                                       ^
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp: In static member function 'static HPHP::{anonymous}::PGSQLResult* HPHP::{anonymous}::PGSQLResult::Get(const HPHP::Variant&)':
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:306:71: error: request for member 'get' in 'HPHP::Variant::toResource() const().HPHP::Resource::getTyped<HPHP::{anonymous}::PGSQLResult>(1, 1)', which is of pointer type 'HPHP::{anonymous}::PGSQLResult*' (maybe you meant to use '->' ?)
       auto *res = result.toResource().getTyped<PGSQLResult>(true, true).get();
                                                                         ^
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp: In member function 'virtual void HPHP::{anonymous}::pgsqlExtension::moduleLoad(const Map&, HPHP::Hdf)':
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1659:90: error: no matching function for call to 'HPHP::Config::GetBool(const Map&, HPHP::Hdf&, const char [16], bool)'
           PGSQL::AllowPersistent     = Config::GetBool(ini,  pgsql, "AllowPersistent", true);
                                                                                            ^
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1659:90: note: candidates are:
  In file included from /usr/include/hphp/runtime/base/runtime-option.h:30:0,
                   from /usr/include/hphp/runtime/base/memory-manager.h:34,
                   from /usr/include/hphp/runtime/base/array-data.h:25,
                   from /usr/include/hphp/runtime/base/array-data-defs.h:20,
                   from /usr/include/hphp/runtime/base/array-iterator.h:23,
                   from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:4:
  /usr/include/hphp/runtime/base/config.h:183:15: note: static bool HPHP::Config::GetBool(const IniSettingMap&, const HPHP::Hdf&, bool)
     static bool GetBool(const IniSettingMap &ini, const Hdf& config,
                 ^
  /usr/include/hphp/runtime/base/config.h:183:15: note:   candidate expects 3 arguments, 4 provided
  /usr/include/hphp/runtime/base/config.h:221:15: note: static bool HPHP::Config::GetBool(const IniSettingMap&, const string&, bool)
     static bool GetBool(const IniSettingMap &ini, const std::string &name,
                 ^
  /usr/include/hphp/runtime/base/config.h:221:15: note:   candidate expects 3 arguments, 4 provided
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1660:86: error: no matching function for call to 'HPHP::Config::GetInt32(const Map&, HPHP::Hdf&, const char [14], int)'
           PGSQL::MaxPersistent       = Config::GetInt32(ini, pgsql, "MaxPersistent", -1);
                                                                                        ^
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1660:86: note: candidates are:
  In file included from /usr/include/hphp/runtime/base/runtime-option.h:30:0,
                   from /usr/include/hphp/runtime/base/memory-manager.h:34,
                   from /usr/include/hphp/runtime/base/array-data.h:25,
                   from /usr/include/hphp/runtime/base/array-data-defs.h:20,
                   from /usr/include/hphp/runtime/base/array-iterator.h:23,
                   from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:4:
  /usr/include/hphp/runtime/base/config.h:197:18: note: static int32_t HPHP::Config::GetInt32(const IniSettingMap&, const HPHP::Hdf&, int32_t)
     static int32_t GetInt32(const IniSettingMap &ini, const Hdf& config,
                    ^
  /usr/include/hphp/runtime/base/config.h:197:18: note:   candidate expects 3 arguments, 4 provided
  /usr/include/hphp/runtime/base/config.h:237:18: note: static int32_t HPHP::Config::GetInt32(const IniSettingMap&, const string&, int32_t)
     static int32_t GetInt32(const IniSettingMap &ini, const std::string &name,
                    ^
  /usr/include/hphp/runtime/base/config.h:237:18: note:   candidate expects 3 arguments, 4 provided
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1661:81: error: no matching function for call to 'HPHP::Config::GetInt32(const Map&, HPHP::Hdf&, const char [9], int)'
           PGSQL::MaxLinks            = Config::GetInt32(ini, pgsql, "MaxLinks", -1);
                                                                                   ^
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:1661:81: note: candidates are:
  In file included from /usr/include/hphp/runtime/base/runtime-option.h:30:0,
                   from /usr/include/hphp/runtime/base/memory-manager.h:34,
                   from /usr/include/hphp/runtime/base/array-data.h:25,
                   from /usr/include/hphp/runtime/base/array-data-defs.h:20,
                   from /usr/include/hphp/runtime/base/array-iterator.h:23,
                   from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:4:
  /usr/include/hphp/runtime/base/config.h:197:18: note: static int32_t HPHP::Config::GetInt32(const IniSettingMap&, const HPHP::Hdf&, int32_t)
     static int32_t GetInt32(const IniSettingMap &ini, const Hdf& config,
                    ^
  /usr/include/hphp/runtime/base/config.h:197:18: note:   candidate expects 3 arguments, 4 provided
  /usr/include/hphp/runtime/base/config.h:237:18: note: static int32_t HPHP::Config::GetInt32(const IniSettingMap&, const string&, int32_t)
     static int32_t GetInt32(const IniSettingMap &ini, const std::string &name,
                    ^
  /usr/include/hphp/runtime/base/config.h:237:18: note:   candidate expects 3 arguments, 4 provided
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp: In static member function 'static HPHP::{anonymous}::PGSQLResult* HPHP::{anonymous}::PGSQLResult::Get(const HPHP::Variant&)':
  /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pgsql.cpp:308:1: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
  make[2]: *** [CMakeFiles/pgsql.dir/pgsql.cpp.o] Error 1
  make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
  make: *** [all] Error 2
  error: Bad exit status from /var/tmp/rpm-tmp.MfP1MD (%build)


  RPM build errors:

**Comment by Aatch** [comment]
There was a small change between 3.7.0 and 3.7.2, there is now a 3.7.2 tag.
