### ISSUE TITLE
build error with HHVM-3.6.1 on ubuntu 14.04 x64

### ISSUE THREAD

**Issue by moonbingbing** [PocketRent/hhvm-pgsql#80]
ming@ubuntu:~/hhvm-pgsql-master$ hhvm --version
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

ming@ubuntu:~/hhvm-pgsql-master$ hphpize 
** hphpize complete, now run `cmake . && make` to build, `make test` to test
ming@ubuntu:~/hhvm-pgsql-master$ cmake . && make
-- Configuring for HHVM API version 20150212
-- pgSQL Include dir: /usr/include/postgresql
-- libpq library: /usr/lib/libpq.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ming/hhvm-pgsql-master
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
In file included from /home/ming/hhvm-pgsql-master/pdo_pgsql_statement.cpp:4:0:
/home/ming/hhvm-pgsql-master/pdo_pgsql.h:10:35: error: conflicting return type specified for ‘virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDOPgSql::createResourceImpl()’
     virtual SmartPtr<PDOResource> createResourceImpl() override;
                                   ^
In file included from /home/ming/hhvm-pgsql-master/pdo_pgsql_resource.h:4:0,
                 from /home/ming/hhvm-pgsql-master/pdo_pgsql_statement.cpp:1:
/usr/include/hphp/runtime/ext/pdo_driver.h:235:24: error:   overriding ‘virtual HPHP::PDOResource* HPHP::PDODriver::createResourceImpl()’
   virtual PDOResource* createResourceImpl() = 0;
                        ^
/home/ming/hhvm-pgsql-master/pdo_pgsql_statement.cpp: In member function ‘bool HPHP::PDOPgSqlStatement::create(const HPHP::String&, const HPHP::Array&)’:
/home/ming/hhvm-pgsql-master/pdo_pgsql_statement.cpp:62:72: error: cannot convert ‘HPHP::sp_PDOStatement {aka HPHP::SmartPtr<HPHP::PDOStatement>}’ to ‘HPHP::PDOStatement*’ for argument ‘1’ to ‘int HPHP::pdo_parse_params(HPHP::PDOStatement*, const HPHP::String&, HPHP::String&)’
             int ret = pdo_parse_params(sp_PDOStatement(this), sql, nsql);
                                                                        ^
make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o] Error 1
make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
make: *** [all] Error 2

How to fix this error? thx

**Comment by tlevi** [comment]
Please try the 3.6.0 tag instead; master branch will only build against hhvm master.

**Comment by adwitama** [comment]
Hi, I had the same problem, but after building it with 3.6.0 tag, the problem did not exist anymore. Many thanks for the help! :)
Btw, I think this project is interesting, anybody know how I can contribute to the repository? Is there any chat rooms or forums for contributors?

**Comment by msingh** [comment]
Hi, I have same problem with HHVM version 3.7.0.

 Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
In file included from /root/hhvm-pgsql-master/pgsql.cpp:2:0:
/root/hhvm-pgsql-master/pgsql.h:6:45: fatal error: hphp/runtime/base/base-includes.h: No such file or directory
 #include "hphp/runtime/base/base-includes.h"
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/pgsql.dir/pgsql.cpp.o] Error 1
make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
make: *** [all] Error 2

How to fix this error?

Thanks.

**Comment by tlevi** [comment]
See #78 for fix.

**Comment by msingh** [comment]
It work now. Thanks.

pgsql.h need to change with this line.
#include "hphp/runtime/ext/extension.h"
