### ISSUE TITLE
Missing includes with HHVM-3.7.0-dev on Centos 7.1.1503

### ISSUE THREAD

**Issue by mattftw** [PocketRent/hhvm-pgsql#81]
[root@localhost hhvm-pgsql]# cat /etc/redhat-release
    CentOS Linux release 7.1.1503 (Core)
    [root@localhost hhvm-pgsql]# hhvm --version
    HipHop VM 3.7.0-dev (rel)
    Compiler: heads/master-0-g6bec157aad74985e64d3d9fe928ad5cc490f5876
    Repo schema: e36ae4255d99eb78d62256c73ee53fadb05d65e0
    [root@localhost hhvm-pgsql]# hphpize
    ** hphpize complete, now run `cmake . && make` to build, `make test` to test
    [root@localhost hhvm-pgsql]# cmake .
    -- Configuring for HHVM API version 20150212
    -- pgSQL Include dir: /usr/include
    -- libpq library: /usr/lib64/libpq.so
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /root/hhvm-pgsql
    [root@localhost hhvm-pgsql]# make
    [ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
    In file included from /root/hhvm-pgsql/pgsql.cpp:2:0:
    /root/hhvm-pgsql/pgsql.h:6:45: fatal error: hphp/runtime/base/base-includes.h: No such file or directory
     #include "hphp/runtime/base/base-includes.h"
                                                 ^
    compilation terminated.
    make[2]: *** [CMakeFiles/pgsql.dir/pgsql.cpp.o] Error 1
    make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
    make: *** [all] Error 2
    [root@localhost hhvm-pgsql]#

I could be missing the hhvm-dev package? What is it, where do i get it?

I originally thought i was doing something wrong, so i made a post on SO:
http://stackoverflow.com/questions/29455059/hhvm-3-7-0-postgresql-pdo

**Comment by tlevi** [comment]
This is #78 ...

**Comment by mattftw** [comment]
Default filters has 'is: issue' so I didn't see the post

Did not realise until just then. My bad.

Will try removing the line and report back.

**Comment by mattftw** [comment]
I removed the include and it worked fine after I installed ``gflags-devel.x86_64``. Maybe add that to the prerequisites as well?

Thanks for the hand!
