### ISSUE TITLE
HHVM 3.7.0 pgsql.so binary

### ISSUE THREAD

**Issue by NinoFloris** [PocketRent/hhvm-pgsql#82]
Has anyone succeeded in compiling pgsql against the latest HHVM version?

EDIT:
Yep, me.

**Comment by NinoFloris** [comment]
base-includes got killed

https://github.com/facebook/hhvm/commit/91e07b951496b5bfbbb189fd5401e9dd5e711c43

**Comment by NinoFloris** [comment]
Fixed

had to change contents of pgsql.h:

````
#include "hphp/runtime/base/base-includes.h"
````
to
````
#include "hphp/runtime/ext/extension.h"
````

succesfully built and linked against https://github.com/facebook/hhvm/commit/c8baf9cd3cb603e030969bfe24634d5e85549915

**Comment by tlevi** [comment]
I'm fairly sure just removing it outright is OK; see #78

**Comment by NinoFloris** [comment]
Ah ok that's fine as well ;)

**Comment by tlevi** [comment]
Yes; unfortunately this isn't merged yet. I'm likely going to need to maintain an up to date fork for internal use soon anyway.
