### ISSUE TITLE
pgsql.so compiled but not work [hhvm 3.7.0]

### ISSUE THREAD

**Issue by gandikun** [PocketRent/hhvm-pgsql#83]
I manage successfully compiled under HHVM 3.7

but when i try to test it, it's return

```
hhvm: symbol lookup error: /usr/lib/hhvm/extensions/pgsql.so: undefined symbol: _ZNK4HPHP9ArrayData6existsEl
```

any clue ?

regard,
Gandi

**Comment by mwpastore** [comment]
Same here, fresh install of hhvm and hhvm-dev on Ubuntu 14.04 LTS with libpq5 9.3.4. Tried a few earlier commits and they either don't compile or generate a pgsql.so that gives the same undefined symbol.

**Comment by gandikun** [comment]
yeah, I following you conversation in #78 

glad to heard not only face this problem, i thought just me :(

**Comment by stentroad** [comment]
I was getting the same thing with 3.8.0.  Try adding the
following to the top of pdo_pgsql.cpp and recompiling.

#include "hphp/runtime/base/array-data.h"
#include "hphp/runtime/base/array-init.h"

**Comment by gandikun** [comment]
@stentroad WoW, It's worked now. Thank you very much.
