### ISSUE TITLE
invalid static_cast from type ‘HPHP::ResourceHdr*’ to type ‘HPHP::{anonymous}::PGSQLResult*’

### ISSUE THREAD

**Issue by ProdigyView** [PocketRent/hhvm-pgsql#98]
/usr/local/include/hphp/runtime/base/type-resource.h:135:53:   required from ‘HPHP::req::ptr<T> HPHP::Resource::getTyped(bool, bool) const [with T = HPHP::{anonymous}::PGSQLResult]’
/root/hhvm-pgsql/pgsql.cpp:306:69:   required from here
/usr/local/include/hphp/runtime/base/req-ptr.h:315:52: error: invalid static_cast from type ‘HPHP::ResourceHdr*’ to type ‘HPHP::{anonymous}::PGSQLResult*’
make[2]: *** [CMakeFiles/pgsql.dir/pgsql.cpp.o] Error 1
make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
make: *** [all] Error 2

**Comment by Aatch** [comment]
Fixed by 160fa5c
